variable "kms_key_id" {
  description = "The ARN for the KMS encryption key. Not Optional."
}

variable "creation_token" {
  description = "(Optional) A unique name (max of 64 characters) used as reference to ensure idempotent file system creation. By default generated by Terraform."
  default     = ""
}

variable "name" {
  description = "The name tag of the file system. Also used in the name of the security group. Different than creation_token"
}

variable "performance_mode" {
  description = "(Optional) The file system performance mode. Can be either 'generalPurpose' or 'maxIO' (Default: 'generalPurpose')."
  default     = "generalPurpose"
}

variable "provisioned_throughput_in_mibps" {
  description = "(Optional) The throughput, measured in MiB/s, that you provision for the file system. Only applicable with throughput_mode set to provisioned."
  default     = "0"
}

variable "throughput_mode" {
  description = "(Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned. When using provisioned, also set provisioned_throughput_in_mibps"
  default     = "bursting"
}

variable "vpc_id" {
  description = "The AWS VPC id of the default EFS mount security group."
}

variable "subnet_ids" {
  description = "A list of subnet ids where efs file mount network interfaces will be created. Must be in same VPC."
  type        = "list"
}

variable "tags" {
  description = "(Optional) A map of tags applied to all resources."
  default     = {}
  type        = "map"
}
